export const items = [
    { name: "Smartphone", price: 699, category: "electronics" },
    { name: "Laptop", price: 1299, category: "electronics" },
    { name: "Smartwatch", price: 199, category: "electronics" },
    { name: "Headphones", price: 149, category: "electronics" },
    { name: "Bluetooth Speaker", price: 99, category: "electronics" },
    { name: "T-Shirt", price: 25, category: "fashion" },
    { name: "Jeans", price: 50, category: "fashion" },
    { name: "Jacket", price: 100, category: "fashion" },
    { name: "Sneakers", price: 80, category: "fashion" },
    { name: "Handbag", price: 60, category: "fashion" },
    { name: "Sofa", price: 500, category: "home items" },
    { name: "Dining Table", price: 750, category: "home items" },
    { name: "Desk Lamp", price: 40, category: "home items" },
    { name: "Curtains", price: 70, category: "home items" },
    { name: "Rug", price: 120, category: "home items" },
    { name: "Tablet", price: 350, category: "electronics" },
    { name: "Blender", price: 150, category: "home items" },
    { name: "Sunglasses", price: 120, category: "fashion" },
    { name: "Gaming Console", price: 499, category: "electronics" },
    { name: "Bookshelf", price: 200, category: "home items" }
  ];